version: '3.8'

services:
  api:
    build:
      context: ./HospitalTierraMedia.API
      dockerfile: Dockerfile
    ports:
      - "28806:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MONGODB__CONNECTIONSTRING=mongodb://mongodb:27017
      - MONGODB__DATABASENAME=HospitalDB
    depends_on:
      - mongodb

  web:
    build:
      context: ./HospitalTierraMedia.Web
      dockerfile: Dockerfile
    ports:
      - "28807:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - api

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - /home/hospital/mongo_data:/data/db